import type { FamousDish } from "@/types"

export const famousDishes: FamousDish[] = [
  // European Dishes
  {
    id: "1",
    name: "Beef Bourguignon",
    origin: "France",
    description: "A classic French beef stew braised in red wine with mushrooms, onions, and bacon.",
    image: "/beef-bourguignon-french-stew.jpg",
    ingredients: ["Beef Chuck", "Red Wine", "Pearl Onions", "Mushrooms", "Bacon", "Carrots", "Garlic", "Thyme"],
    difficulty: "Hard",
  },
  {
    id: "2",
    name: "Paella Valenciana",
    origin: "Spain",
    description: "Traditional Spanish rice dish with chicken, rabbit, and vegetables.",
    image: "/paella-valenciana-spanish-rice.jpg",
    ingredients: ["Rice", "Chicken", "Rabbit", "Green Beans", "Butter Beans", "Saffron", "Paprika", "Olive Oil"],
    difficulty: "Medium",
  },
  {
    id: "3",
    name: "Wiener Schnitzel",
    origin: "Austria",
    description: "Breaded and fried veal cutlet, a beloved Austrian classic.",
    image: "/wiener-schnitzel-austrian-veal.jpg",
    ingredients: ["Veal Cutlets", "Flour", "Eggs", "Breadcrumbs", "Lemon", "Butter", "Parsley"],
    difficulty: "Medium",
  },
  // Italian Dishes
  {
    id: "4",
    name: "Osso Buco",
    origin: "Italy",
    description: "Milanese specialty of braised veal shanks with gremolata.",
    image: "/osso-buco-italian-veal-shanks.jpg",
    ingredients: ["Veal Shanks", "White Wine", "Tomatoes", "Carrots", "Celery", "Onion", "Lemon Zest", "Parsley"],
    difficulty: "Hard",
  },
  {
    id: "5",
    name: "Risotto alla Milanese",
    origin: "Italy",
    description: "Creamy saffron-infused risotto from Milan.",
    image: "/risotto-milanese-saffron-rice.jpg",
    ingredients: ["Arborio Rice", "Saffron", "Parmesan", "White Wine", "Butter", "Onion", "Beef Stock"],
    difficulty: "Medium",
  },
  {
    id: "6",
    name: "Carbonara",
    origin: "Italy",
    description: "Roman pasta dish with eggs, pecorino cheese, guanciale, and black pepper.",
    image: "/carbonara-pasta-italian-eggs.jpg",
    ingredients: ["Spaghetti", "Guanciale", "Eggs", "Pecorino Romano", "Black Pepper"],
    difficulty: "Medium",
  },
  // Japanese Dishes
  {
    id: "7",
    name: "Tonkatsu",
    origin: "Japan",
    description: "Breaded and deep-fried pork cutlet served with tangy sauce.",
    image: "/tonkatsu-japanese-pork-cutlet.jpg",
    ingredients: ["Pork Loin", "Panko", "Eggs", "Flour", "Cabbage", "Tonkatsu Sauce", "Rice"],
    difficulty: "Easy",
  },
  {
    id: "8",
    name: "Ramen",
    origin: "Japan",
    description: "Japanese noodle soup with rich broth, noodles, and various toppings.",
    image: "/ramen-japanese-noodle-soup.jpg",
    ingredients: [
      "Ramen Noodles",
      "Pork Belly",
      "Soft-Boiled Eggs",
      "Nori",
      "Green Onions",
      "Miso",
      "Soy Sauce",
      "Chicken Stock",
    ],
    difficulty: "Hard",
  },
  {
    id: "9",
    name: "Sushi",
    origin: "Japan",
    description: "Vinegared rice with fresh fish and vegetables.",
    image: "/sushi-japanese-rice-fish.jpg",
    ingredients: ["Sushi Rice", "Nori", "Fresh Salmon", "Tuna", "Avocado", "Cucumber", "Wasabi", "Soy Sauce"],
    difficulty: "Hard",
  },
  // American Dishes
  {
    id: "10",
    name: "BBQ Ribs",
    origin: "USA",
    description: "Slow-cooked pork ribs with smoky barbecue sauce.",
    image: "/bbq-ribs-american-pork.jpg",
    ingredients: ["Pork Ribs", "BBQ Sauce", "Brown Sugar", "Paprika", "Garlic Powder", "Onion Powder", "Black Pepper"],
    difficulty: "Medium",
  },
  {
    id: "11",
    name: "Lobster Roll",
    origin: "USA",
    description: "New England specialty with fresh lobster meat in a buttered roll.",
    image: "/lobster-roll-american-seafood.jpg",
    ingredients: ["Lobster Meat", "Butter", "Lemon", "Celery", "Mayonnaise", "Hot Dog Buns", "Chives"],
    difficulty: "Easy",
  },
  {
    id: "12",
    name: "Gumbo",
    origin: "USA",
    description: "Louisiana stew with seafood, sausage, and okra over rice.",
    image: "/gumbo-louisiana-stew-seafood.jpg",
    ingredients: ["Shrimp", "Andouille Sausage", "Okra", "Bell Peppers", "Celery", "Onion", "Rice", "Cajun Spices"],
    difficulty: "Hard",
  },
  // South African Dishes
  {
    id: "13",
    name: "Bobotie",
    origin: "South Africa",
    description: "Spiced minced meat baked with an egg topping.",
    image: "/bobotie-south-african-meat-curry.jpg",
    ingredients: ["Ground Beef", "Curry Powder", "Dried Apricots", "Almonds", "Eggs", "Milk", "Bread", "Onion"],
    difficulty: "Medium",
  },
  {
    id: "14",
    name: "Bunny Chow",
    origin: "South Africa",
    description: "Hollowed-out bread loaf filled with curry.",
    image: "/bunny-chow-south-african-curry-bread.jpg",
    ingredients: ["Bread Loaf", "Lamb Curry", "Potatoes", "Curry Spices", "Tomatoes", "Onions", "Garlic", "Ginger"],
    difficulty: "Medium",
  },
  {
    id: "15",
    name: "Boerewors",
    origin: "South Africa",
    description: "Traditional South African sausage with distinctive spices.",
    image: "/boerewors-south-african-sausage.jpg",
    ingredients: ["Beef", "Pork", "Coriander", "Black Pepper", "Nutmeg", "Cloves", "Vinegar"],
    difficulty: "Easy",
  },
]
